export interface CountryOption {
  code: string;
  name: string;
  english: string;
}

export const COUNTRIES: readonly CountryOption[] = [
  { code: "AF", name: "Afganistan", english: "Afghanistan" },
  { code: "DE", name: "Almanya", english: "Germany" },
  { code: "US", name: "Amerika Birleşik Devletleri", english: "United States" },
  { code: "AD", name: "Andorra", english: "Andorra" },
  { code: "AO", name: "Angola", english: "Angola" },
  { code: "AG", name: "Antigua ve Barbuda", english: "Antigua & Barbuda" },
  { code: "AR", name: "Arjantin", english: "Argentina" },
  { code: "AL", name: "Arnavutluk", english: "Albania" },
  { code: "AU", name: "Avustralya", english: "Australia" },
  { code: "AT", name: "Avusturya", english: "Austria" },
  { code: "AZ", name: "Azerbaycan", english: "Azerbaijan" },
  { code: "BS", name: "Bahamalar", english: "Bahamas" },
  { code: "BH", name: "Bahreyn", english: "Bahrain" },
  { code: "BD", name: "Bangladeş", english: "Bangladesh" },
  { code: "BB", name: "Barbados", english: "Barbados" },
  { code: "BY", name: "Belarus", english: "Belarus" },
  { code: "BE", name: "Belçika", english: "Belgium" },
  { code: "BZ", name: "Belize", english: "Belize" },
  { code: "BJ", name: "Benin", english: "Benin" },
  { code: "AE", name: "Birleşik Arap Emirlikleri", english: "United Arab Emirates" },
  { code: "GB", name: "Birleşik Krallık", english: "United Kingdom" },
  { code: "BO", name: "Bolivya", english: "Bolivia" },
  { code: "BA", name: "Bosna-Hersek", english: "Bosnia & Herzegovina" },
  { code: "BW", name: "Botsvana", english: "Botswana" },
  { code: "BR", name: "Brezilya", english: "Brazil" },
  { code: "BN", name: "Brunei", english: "Brunei" },
  { code: "BG", name: "Bulgaristan", english: "Bulgaria" },
  { code: "BF", name: "Burkina Faso", english: "Burkina Faso" },
  { code: "BI", name: "Burundi", english: "Burundi" },
  { code: "BT", name: "Butan", english: "Bhutan" },
  { code: "CV", name: "Cabo Verde", english: "Cape Verde" },
  { code: "DZ", name: "Cezayir", english: "Algeria" },
  { code: "DJ", name: "Cibuti", english: "Djibouti" },
  { code: "CI", name: "Côte d’Ivoire", english: "Côte d’Ivoire" },
  { code: "TD", name: "Çad", english: "Chad" },
  { code: "CZ", name: "Çekya", english: "Czechia" },
  { code: "CN", name: "Çin", english: "China" },
  { code: "HK", name: "Çin Hong Kong ÖİB", english: "Hong Kong SAR China" },
  { code: "MO", name: "Çin Makao ÖİB", english: "Macao SAR China" },
  { code: "DK", name: "Danimarka", english: "Denmark" },
  { code: "DO", name: "Dominik Cumhuriyeti", english: "Dominican Republic" },
  { code: "DM", name: "Dominika", english: "Dominica" },
  { code: "EC", name: "Ekvador", english: "Ecuador" },
  { code: "GQ", name: "Ekvator Ginesi", english: "Equatorial Guinea" },
  { code: "SV", name: "El Salvador", english: "El Salvador" },
  { code: "ID", name: "Endonezya", english: "Indonesia" },
  { code: "ER", name: "Eritre", english: "Eritrea" },
  { code: "AM", name: "Ermenistan", english: "Armenia" },
  { code: "EE", name: "Estonya", english: "Estonia" },
  { code: "SZ", name: "Esvatini", english: "Eswatini" },
  { code: "ET", name: "Etiyopya", english: "Ethiopia" },
  { code: "MA", name: "Fas", english: "Morocco" },
  { code: "FJ", name: "Fiji", english: "Fiji" },
  { code: "PH", name: "Filipinler", english: "Philippines" },
  { code: "PS", name: "Filistin Bölgeleri", english: "Palestinian Territories" },
  { code: "FI", name: "Finlandiya", english: "Finland" },
  { code: "FR", name: "Fransa", english: "France" },
  { code: "GA", name: "Gabon", english: "Gabon" },
  { code: "GM", name: "Gambiya", english: "Gambia" },
  { code: "GH", name: "Gana", english: "Ghana" },
  { code: "GN", name: "Gine", english: "Guinea" },
  { code: "GW", name: "Gine-Bissau", english: "Guinea-Bissau" },
  { code: "GD", name: "Grenada", english: "Grenada" },
  { code: "GT", name: "Guatemala", english: "Guatemala" },
  { code: "GY", name: "Guyana", english: "Guyana" },
  { code: "ZA", name: "Güney Afrika", english: "South Africa" },
  { code: "KR", name: "Güney Kore", english: "South Korea" },
  { code: "SS", name: "Güney Sudan", english: "South Sudan" },
  { code: "GE", name: "Gürcistan", english: "Georgia" },
  { code: "HT", name: "Haiti", english: "Haiti" },
  { code: "HR", name: "Hırvatistan", english: "Croatia" },
  { code: "IN", name: "Hindistan", english: "India" },
  { code: "NL", name: "Hollanda", english: "Netherlands" },
  { code: "HN", name: "Honduras", english: "Honduras" },
  { code: "IQ", name: "Irak", english: "Iraq" },
  { code: "IR", name: "İran", english: "Iran" },
  { code: "IE", name: "İrlanda", english: "Ireland" },
  { code: "ES", name: "İspanya", english: "Spain" },
  { code: "IL", name: "İsrail", english: "Israel" },
  { code: "SE", name: "İsveç", english: "Sweden" },
  { code: "CH", name: "İsviçre", english: "Switzerland" },
  { code: "IT", name: "İtalya", english: "Italy" },
  { code: "IS", name: "İzlanda", english: "Iceland" },
  { code: "JM", name: "Jamaika", english: "Jamaica" },
  { code: "JP", name: "Japonya", english: "Japan" },
  { code: "KH", name: "Kamboçya", english: "Cambodia" },
  { code: "CM", name: "Kamerun", english: "Cameroon" },
  { code: "CA", name: "Kanada", english: "Canada" },
  { code: "ME", name: "Karadağ", english: "Montenegro" },
  { code: "QA", name: "Katar", english: "Qatar" },
  { code: "KZ", name: "Kazakistan", english: "Kazakhstan" },
  { code: "KE", name: "Kenya", english: "Kenya" },
  { code: "CY", name: "Kıbrıs", english: "Cyprus" },
  { code: "KG", name: "Kırgızistan", english: "Kyrgyzstan" },
  { code: "KI", name: "Kiribati", english: "Kiribati" },
  { code: "CO", name: "Kolombiya", english: "Colombia" },
  { code: "KM", name: "Komorlar", english: "Comoros" },
  { code: "CG", name: "Kongo - Brazavil", english: "Congo - Brazzaville" },
  { code: "CD", name: "Kongo - Kinşasa", english: "Congo - Kinshasa" },
  { code: "XK", name: "Kosova", english: "Kosovo" },
  { code: "CR", name: "Kosta Rika", english: "Costa Rica" },
  { code: "KW", name: "Kuveyt", english: "Kuwait" },
  { code: "KP", name: "Kuzey Kore", english: "North Korea" },
  { code: "MK", name: "Kuzey Makedonya", english: "North Macedonia" },
  { code: "CU", name: "Küba", english: "Cuba" },
  { code: "LA", name: "Laos", english: "Laos" },
  { code: "LS", name: "Lesotho", english: "Lesotho" },
  { code: "LV", name: "Letonya", english: "Latvia" },
  { code: "LR", name: "Liberya", english: "Liberia" },
  { code: "LY", name: "Libya", english: "Libya" },
  { code: "LI", name: "Liechtenstein", english: "Liechtenstein" },
  { code: "LT", name: "Litvanya", english: "Lithuania" },
  { code: "LB", name: "Lübnan", english: "Lebanon" },
  { code: "LU", name: "Lüksemburg", english: "Luxembourg" },
  { code: "HU", name: "Macaristan", english: "Hungary" },
  { code: "MG", name: "Madagaskar", english: "Madagascar" },
  { code: "MW", name: "Malavi", english: "Malawi" },
  { code: "MV", name: "Maldivler", english: "Maldives" },
  { code: "MY", name: "Malezya", english: "Malaysia" },
  { code: "ML", name: "Mali", english: "Mali" },
  { code: "MT", name: "Malta", english: "Malta" },
  { code: "MH", name: "Marshall Adaları", english: "Marshall Islands" },
  { code: "MU", name: "Mauritius", english: "Mauritius" },
  { code: "MX", name: "Meksika", english: "Mexico" },
  { code: "EG", name: "Mısır", english: "Egypt" },
  { code: "FM", name: "Mikronezya", english: "Micronesia" },
  { code: "MN", name: "Moğolistan", english: "Mongolia" },
  { code: "MD", name: "Moldova", english: "Moldova" },
  { code: "MC", name: "Monako", english: "Monaco" },
  { code: "MR", name: "Moritanya", english: "Mauritania" },
  { code: "MZ", name: "Mozambik", english: "Mozambique" },
  { code: "MM", name: "Myanmar (Burma)", english: "Myanmar (Burma)" },
  { code: "NA", name: "Namibya", english: "Namibia" },
  { code: "NR", name: "Nauru", english: "Nauru" },
  { code: "NP", name: "Nepal", english: "Nepal" },
  { code: "NE", name: "Nijer", english: "Niger" },
  { code: "NG", name: "Nijerya", english: "Nigeria" },
  { code: "NI", name: "Nikaragua", english: "Nicaragua" },
  { code: "NO", name: "Norveç", english: "Norway" },
  { code: "CF", name: "Orta Afrika Cumhuriyeti", english: "Central African Republic" },
  { code: "UZ", name: "Özbekistan", english: "Uzbekistan" },
  { code: "PK", name: "Pakistan", english: "Pakistan" },
  { code: "PW", name: "Palau", english: "Palau" },
  { code: "PA", name: "Panama", english: "Panama" },
  { code: "PG", name: "Papua Yeni Gine", english: "Papua New Guinea" },
  { code: "PY", name: "Paraguay", english: "Paraguay" },
  { code: "PE", name: "Peru", english: "Peru" },
  { code: "PL", name: "Polonya", english: "Poland" },
  { code: "PT", name: "Portekiz", english: "Portugal" },
  { code: "RO", name: "Romanya", english: "Romania" },
  { code: "RW", name: "Ruanda", english: "Rwanda" },
  { code: "RU", name: "Rusya", english: "Russia" },
  { code: "KN", name: "Saint Kitts ve Nevis", english: "St. Kitts & Nevis" },
  { code: "LC", name: "Saint Lucia", english: "St. Lucia" },
  { code: "VC", name: "Saint Vincent ve Grenadinler", english: "St. Vincent & Grenadines" },
  { code: "WS", name: "Samoa", english: "Samoa" },
  { code: "SM", name: "San Marino", english: "San Marino" },
  { code: "ST", name: "Sao Tome ve Principe", english: "São Tomé & Príncipe" },
  { code: "SN", name: "Senegal", english: "Senegal" },
  { code: "SC", name: "Seyşeller", english: "Seychelles" },
  { code: "RS", name: "Sırbistan", english: "Serbia" },
  { code: "SL", name: "Sierra Leone", english: "Sierra Leone" },
  { code: "SG", name: "Singapur", english: "Singapore" },
  { code: "SK", name: "Slovakya", english: "Slovakia" },
  { code: "SI", name: "Slovenya", english: "Slovenia" },
  { code: "SB", name: "Solomon Adaları", english: "Solomon Islands" },
  { code: "SO", name: "Somali", english: "Somalia" },
  { code: "LK", name: "Sri Lanka", english: "Sri Lanka" },
  { code: "SD", name: "Sudan", english: "Sudan" },
  { code: "SR", name: "Surinam", english: "Suriname" },
  { code: "SY", name: "Suriye", english: "Syria" },
  { code: "SA", name: "Suudi Arabistan", english: "Saudi Arabia" },
  { code: "CL", name: "Şili", english: "Chile" },
  { code: "TJ", name: "Tacikistan", english: "Tajikistan" },
  { code: "TZ", name: "Tanzanya", english: "Tanzania" },
  { code: "TH", name: "Tayland", english: "Thailand" },
  { code: "TW", name: "Tayvan", english: "Taiwan" },
  { code: "TL", name: "Timor-Leste", english: "Timor-Leste" },
  { code: "TG", name: "Togo", english: "Togo" },
  { code: "TO", name: "Tonga", english: "Tonga" },
  { code: "TT", name: "Trinidad ve Tobago", english: "Trinidad & Tobago" },
  { code: "TN", name: "Tunus", english: "Tunisia" },
  { code: "TV", name: "Tuvalu", english: "Tuvalu" },
  { code: "TR", name: "Türkiye", english: "Türkiye" },
  { code: "TM", name: "Türkmenistan", english: "Turkmenistan" },
  { code: "UG", name: "Uganda", english: "Uganda" },
  { code: "UA", name: "Ukrayna", english: "Ukraine" },
  { code: "OM", name: "Umman", english: "Oman" },
  { code: "UY", name: "Uruguay", english: "Uruguay" },
  { code: "JO", name: "Ürdün", english: "Jordan" },
  { code: "VU", name: "Vanuatu", english: "Vanuatu" },
  { code: "VA", name: "Vatikan", english: "Vatican City" },
  { code: "VE", name: "Venezuela", english: "Venezuela" },
  { code: "VN", name: "Vietnam", english: "Vietnam" },
  { code: "YE", name: "Yemen", english: "Yemen" },
  { code: "NZ", name: "Yeni Zelanda", english: "New Zealand" },
  { code: "GR", name: "Yunanistan", english: "Greece" },
  { code: "ZM", name: "Zambiya", english: "Zambia" },
  { code: "ZW", name: "Zimbabve", english: "Zimbabwe" },
];

export function countryFlag(code: string): string {
  if (!/^[A-Za-z]{2}$/.test(code)) return '';
  return [...code.toUpperCase()].map((char) => String.fromCodePoint(127397 + char.charCodeAt(0))).join('');
}

export function countryByCode(code: string | null | undefined): CountryOption | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((item) => item.code === code.toUpperCase());
}
