import { colors } from '@dating/ui/tokens';
import { StyleSheet } from 'react-native';

export { colors };

export const ui = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bgBottom,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  screenContent: {
    flexGrow: 1,
    gap: 22,
  },
  meter: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.surface2,
    overflow: 'hidden',
  },
  meterFill: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  title: { color: colors.text, fontSize: 28, fontWeight: '700' },
  subtitle: { color: colors.textMuted, fontSize: 15, lineHeight: 22 },
  input: {
    backgroundColor: colors.surface,
    color: colors.text,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  inputWrap: { position: 'relative', justifyContent: 'center' },
  reveal: {
    position: 'absolute',
    right: 6,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primary: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondary: {
    backgroundColor: colors.surface2,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
  },
  ghost: {
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryText: { color: colors.bgBottom, fontWeight: '700', fontSize: 16 },
  secondaryText: { color: colors.text, fontWeight: '600', fontSize: 16 },
  hint: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  error: { color: colors.danger, fontSize: 14 },
  alertDanger: {
    backgroundColor: `${colors.danger}22`,
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  alertSuccess: {
    backgroundColor: `${colors.success}22`,
    borderColor: colors.success,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  alertDangerText: { color: colors.text, fontSize: 14, lineHeight: 20 },
  alertSuccessText: { color: colors.text, fontSize: 14, lineHeight: 20 },
  google: {
    backgroundColor: colors.text,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  googleText: { color: colors.bgBottom, fontWeight: '700', fontSize: 16 },
  googleMark: {
    width: 22,
    height: 22,
    borderRadius: 11,
    overflow: 'hidden',
    backgroundColor: colors.text,
  },
  googleSlice: { position: 'absolute', width: 11, height: 11 },
  googleSliceBlue: { top: 0, left: 0, backgroundColor: '#4285F4' },
  googleSliceRed: { top: 0, right: 0, backgroundColor: '#EA4335' },
  googleSliceYellow: { bottom: 0, left: 0, backgroundColor: '#FBBC05' },
  googleSliceGreen: { bottom: 0, right: 0, backgroundColor: '#34A853' },
  googleCore: {
    position: 'absolute',
    top: 4,
    left: 4,
    right: 4,
    bottom: 4,
    borderRadius: 8,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleLetter: { color: '#4285F4', fontWeight: '800', fontSize: 13, lineHeight: 16 },
  divider: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.surface2 },
  dividerText: { color: colors.textMuted, fontSize: 13 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    overflow: 'hidden',
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.surface2,
  },
  chipOn: { backgroundColor: colors.primary },
  chipText: { color: colors.text, fontSize: 14 },
  chipTextOn: { color: colors.bgBottom, fontWeight: '700' },
  row: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  fieldLabel: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pageIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMark: {
    width: 88,
    height: 88,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centered: { textAlign: 'center' },
  photoCell: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCover: { borderWidth: 2, borderColor: colors.primary },
  photoSelected: { borderWidth: 2, borderColor: colors.primarySoft },
  photoBadge: {
    position: 'absolute',
    left: 6,
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  photoBadgeTop: { top: 6 },
  photoBadgeBottom: { bottom: 6 },
  photoBadgeText: { color: colors.bgBottom, fontSize: 11, fontWeight: '700' },
  select: {
    minHeight: 52,
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  selectText: { color: colors.text, fontSize: 16, flex: 1 },
  selectPlaceholder: { color: colors.textMuted, fontSize: 16, flex: 1 },
  menu: {
    maxHeight: 220,
    backgroundColor: colors.surface,
    borderRadius: 14,
    overflow: 'hidden',
  },
  menuSearch: {
    borderBottomWidth: 1,
    borderBottomColor: colors.surface2,
  },
  option: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface2,
  },
});
