ALTER TABLE "user_profiles"
  ADD COLUMN "smartPhotos" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "hideAge" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "hideDistance" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "obsession" TEXT,
  ADD COLUMN "watched" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "movies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "teams" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "games" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "songs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "artists" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
