INSERT INTO "interests" ("slug", "name", "category", "sortOrder") VALUES
  ('fitness', 'Fitness', 'Spor ve Aktivite', 1),
  ('yoga', 'Yoga', 'Spor ve Aktivite', 2),
  ('running', 'Koşu', 'Spor ve Aktivite', 3),
  ('hiking', 'Doğa yürüyüşü', 'Spor ve Aktivite', 4),
  ('cycling', 'Bisiklet', 'Spor ve Aktivite', 5),
  ('swimming', 'Yüzme', 'Spor ve Aktivite', 6),
  ('football', 'Futbol', 'Spor ve Aktivite', 7),
  ('basketball', 'Basketbol', 'Spor ve Aktivite', 8),
  ('tennis', 'Tenis', 'Spor ve Aktivite', 9),
  ('climbing', 'Tırmanış', 'Spor ve Aktivite', 10),
  ('music', 'Müzik', 'Sanat ve Kültür', 11),
  ('concerts', 'Konserler', 'Sanat ve Kültür', 12),
  ('cinema', 'Sinema', 'Sanat ve Kültür', 13),
  ('theatre', 'Tiyatro', 'Sanat ve Kültür', 14),
  ('photography', 'Fotoğrafçılık', 'Sanat ve Kültür', 15),
  ('painting', 'Resim', 'Sanat ve Kültür', 16),
  ('reading', 'Kitap okumak', 'Sanat ve Kültür', 17),
  ('writing', 'Yazmak', 'Sanat ve Kültür', 18),
  ('museums', 'Müzeler', 'Sanat ve Kültür', 19),
  ('dance', 'Dans', 'Sanat ve Kültür', 20),
  ('cooking', 'Yemek yapmak', 'Yeme İçme', 21),
  ('coffee', 'Kahve', 'Yeme İçme', 22),
  ('wine', 'Şarap', 'Yeme İçme', 23),
  ('street-food', 'Sokak lezzetleri', 'Yeme İçme', 24),
  ('vegan', 'Vegan mutfak', 'Yeme İçme', 25),
  ('baking', 'Pasta ve fırın', 'Yeme İçme', 26),
  ('travel', 'Seyahat', 'Yaşam Tarzı', 27),
  ('camping', 'Kamp', 'Yaşam Tarzı', 28),
  ('pets', 'Evcil hayvanlar', 'Yaşam Tarzı', 29),
  ('gardening', 'Bahçecilik', 'Yaşam Tarzı', 30),
  ('meditation', 'Meditasyon', 'Yaşam Tarzı', 31),
  ('volunteering', 'Gönüllülük', 'Yaşam Tarzı', 32),
  ('fashion', 'Moda', 'Yaşam Tarzı', 33),
  ('gaming', 'Video oyunları', 'Teknoloji ve Oyun', 34),
  ('board-games', 'Kutu oyunları', 'Teknoloji ve Oyun', 35),
  ('technology', 'Teknoloji', 'Teknoloji ve Oyun', 36),
  ('science', 'Bilim', 'Teknoloji ve Oyun', 37),
  ('podcasts', 'Podcast', 'Teknoloji ve Oyun', 38),
  ('anime', 'Anime', 'Teknoloji ve Oyun', 39)
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "sortOrder" = EXCLUDED."sortOrder";
